--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."BOARD" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_TITLE" VARCHAR2(300 BYTE), 
	"BOARD_CONTENT" VARCHAR2(1000 BYTE), 
	"BOARD_WRITER" VARCHAR2(20 BYTE), 
	"READ_COUNT" NUMBER, 
	"REG_DATE" CHAR(10 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILEPATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"PHONE" CHAR(13 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"MEMBER_LEVEL" NUMBER, 
	"ENROLL_DATE" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(300 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(20 BYTE), 
	"READ_COUNT" NUMBER, 
	"REG_DATE" CHAR(10 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILEPATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_COMMENT
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."NOTICE_COMMENT" 
   (	"NC_NO" NUMBER, 
	"NC_LEVEL" NUMBER, 
	"NC_WRITER" VARCHAR2(20 BYTE), 
	"NC_CONTENT" VARCHAR2(500 BYTE), 
	"NC_DATE" CHAR(10 BYTE), 
	"NOTICE_REF" NUMBER, 
	"NC_REF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."PHOTO" 
   (	"PHOTO_NO" NUMBER, 
	"PHOTO_WRITER" VARCHAR2(20 BYTE), 
	"PHOTO_COMMENT" VARCHAR2(100 BYTE), 
	"PHOTO_DATE" CHAR(10 BYTE), 
	"FILEPATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBSERVER"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBSERVER"."MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBSERVER"."NC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBSERVER"."NOTICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PHOTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WEBSERVER"."PHOTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into WEBSERVER.BOARD
SET DEFINE OFF;
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (1,'asd','asd','미누당1',1,'2021-10-05','mvc2 특징.jpg','mvc2 특징.jpg');
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (2,'wqeqw','wqeq','미누당1',4,'2021-10-05','mvc2 특징.jpg','mvc2 특징1.jpg');
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (3,'3게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (4,'4게시글','테스트','admin',1,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (5,'5게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (6,'6게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (7,'7게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (8,'8게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (9,'9게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (10,'10게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (11,'11게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (12,'12게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (13,'13게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (14,'14게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (15,'15게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (16,'16게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (17,'17게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (18,'18게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (19,'19게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (20,'20게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (21,'21게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (22,'22게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (23,'23게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (24,'24게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (25,'25게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (26,'26게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (27,'27게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (28,'28게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (29,'29게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (30,'30게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (31,'31게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (32,'32게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (33,'33게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (34,'34게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (35,'35게시글','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (36,'36게시글','테스트','admin',1,'2021-10-06',null,null);
Insert into WEBSERVER.BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (37,'37게시글','테스트','admin',1,'2021-10-06',null,null);
REM INSERTING into WEBSERVER.MEMBER
SET DEFINE OFF;
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (1,'ㅁㄴㅇ','213','sad','213432444    ','asdeqtffcv212sada',2,'2021-09-30');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (2,'미누당1','1234','정민우','010-1234-1258','변경했다~',2,'2021-09-30');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (22,'테스트','1234','테스트용','010-1234-1324','테스트용',2,'2021-09-30');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (23,'admin','1234','관리자','010-9999-9999','회사',1,'2021-09-30');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (26,'test1','1234','테스터','010-9999-9999','회사',2,'2021-10-01');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (33,'user00','1234','유저0','010-0000-0000','1234',2,'2021-10-04');
Insert into WEBSERVER.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,PHONE,ADDRESS,MEMBER_LEVEL,ENROLL_DATE) values (34,'민우다요','1234','정민호우','010-2154-8547','강서구',2,'2021-10-04');
REM INSERTING into WEBSERVER.NOTICE
SET DEFINE OFF;
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (1,'adas','sad','admin',0,'2021-10-05',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (4,'asdas','asdsa','admin',0,'2021-10-05','1.jpg','14.jpg');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (5,'5공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (6,'6공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (7,'7공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (8,'8공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (9,'9공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (10,'10공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (11,'11공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (12,'12공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (13,'13공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (14,'14공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (15,'15공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (16,'16공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (17,'17공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (18,'18공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (19,'19공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (20,'20공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (21,'21공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (22,'22공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (23,'23공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (24,'24공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (25,'25공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (26,'26공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (27,'27공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (28,'28공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (29,'29공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (30,'30공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (31,'31공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (32,'32공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (33,'33공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (34,'34공지','테스트asdasd','admin',2,'2021-10-06','1.jpg','16.jpg');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (35,'35공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (36,'36공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (37,'37공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (38,'38공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (39,'39공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (40,'40공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (41,'41공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (42,'42공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (43,'43공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (44,'44공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (45,'45공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (46,'46공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (47,'47공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (48,'48공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (49,'49공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (50,'50공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (51,'51공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (52,'52공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (53,'53공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (54,'54공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (55,'55공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (56,'56공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (57,'57공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (58,'58공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (59,'59공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (60,'60공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (61,'61공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (62,'62공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (63,'63공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (64,'64공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (65,'65공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (66,'66공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (67,'67공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (68,'68공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (69,'69공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (70,'70공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (71,'71공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (72,'72공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (73,'73공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (74,'74공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (75,'75공지','테스트','admin',1,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (76,'76공지','테스트','admin',1,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (77,'77공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (78,'78공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (79,'79공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (80,'80공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (81,'81공지','테스트','admin',0,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (82,'82공지(수정)','<p>테스트</p><p><img src="/upload/editor/img12.jpg" style="width: 938.547px;"><br></p>','admin',32,'2021-10-06',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (102,'에디터 이미지 테스트','<p>ㄹㄹㄹ</p><p><img src="/upload/editor/img091.jpg" style="width: 938.547px;"><br></p>','admin',5,'2021-10-14',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (85,'파일다운로드','ㄴㅁㅇㅁㄴㅇㅁ
ㅁㄴㅇ
ㅁㄴㅇ
ㅇㅁㄴㅇ
ㅁㄴㅇㄴㄴㅁ

','admin',15,'2021-10-06','KakaoTalk_20210223_192826642.jpg','KakaoTalk_20210223_192826642.jpg');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,NOTICE_WRITER,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (121,'sadasd','<p><img src="/upload/editor/정민우.jpg" style="width: 938.547px;"><br></p>','admin',1,'2021-10-27',null,null);
REM INSERTING into WEBSERVER.NOTICE_COMMENT
SET DEFINE OFF;
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_LEVEL,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (1,1,'미누당1','확인했어용','2021-10-08',82,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_LEVEL,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (3,2,'admin','asdas','2021-10-08',82,1);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_LEVEL,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (6,1,'admin','수정했지롱','2021-10-08',85,null);
REM INSERTING into WEBSERVER.PHOTO
SET DEFINE OFF;
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (1,'미누당1','자연','2021-10-11','img03.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (2,'미누당1','asd','2021-10-12','img12.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (3,'미누당1','asdas','2021-10-12','img15.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (4,'미누당1','asdas','2021-10-12','img02.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (5,'미누당1','asdsa','2021-10-12','img20.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_COMMENT,PHOTO_DATE,FILEPATH) values (6,'미누당1','asd','2021-10-12','img13.jpg');
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."MEMBER" ADD UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."MEMBER" ADD PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("MEMBER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD PRIMARY KEY ("NC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" MODIFY ("NC_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."BOARD" ADD PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."BOARD" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."PHOTO" ADD PRIMARY KEY ("PHOTO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."PHOTO" MODIFY ("PHOTO_COMMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."BOARD" ADD FOREIGN KEY ("BOARD_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE" ADD FOREIGN KEY ("NOTICE_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NC_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NOTICE_REF")
	  REFERENCES "WEBSERVER"."NOTICE" ("NOTICE_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NC_REF")
	  REFERENCES "WEBSERVER"."NOTICE_COMMENT" ("NC_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."PHOTO" ADD FOREIGN KEY ("PHOTO_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
