CREATE TABLE USER_TBL(
    USER_NO     NUMBER          PRIMARY KEY,
    USER_ID     VARCHAR2(20)    NOT NULL,
    USER_PW     VARCHAR2(30)    NOT NULL,
    USER_NAME   VARCHAR2(15)    NOT NULL,
    USER_AGE    NUMBER          NOT NULL,
    USER_PHONE  CHAR(13)        NOT NULL,
    UNIQUE(USER_ID)
);
/

COMMENT ON COLUMN USER_TBL.USER_NO IS '회원번호';


COMMENT ON COLUMN USER_TBL.USER_ID IS '아이디';


COMMENT ON COLUMN USER_TBL.USER_PW IS '비밀번호';


COMMENT ON COLUMN USER_TBL.USER_NAME IS '이름';


COMMENT ON COLUMN USER_TBL.USER_AGE IS '나이';


COMMENT ON COLUMN USER_TBL.USER_PHONE IS '전화번호';

CREATE SEQUENCE SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE
;

--  SELECT COUNT(*) FROM USER_TBL WHERE USER_ID = ?

COMMIT;

SELECT * FROM USER_TBL;
SELECT * FROM BOARD_TBL;


CREATE TABLE BOARD_TBL(
    BOARD_NO        NUMBER          PRIMARY KEY,
    BOARD_TITLE     VARCHAR2(100),
    BOARD_CONTENT   VARCHAR2(300),
    BOARD_WRITER    NUMBER          REFERENCES USER_TBL (USER_NO) ON DELETE SET NULL,
    READ_COUNT      NUMBER          DEFAULT 0,
    ENROLL_DATE     DATE            DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD_TBL.BOARD_NO IS '게시글 번호';

COMMENT ON COLUMN BOARD_TBL.BOARD_TITLE IS '게시글 제목';

COMMENT ON COLUMN BOARD_TBL.BOARD_CONTENT IS '게시글 내용';

COMMENT ON COLUMN BOARD_TBL.BOARD_WRITER IS '작성자';

COMMENT ON COLUMN BOARD_TBL.READ_COUNT IS '조회수';

COMMENT ON COLUMN BOARD_TBL.ENROLL_DATE IS '작성일';

CREATE SEQUENCE SEQ_BOARD
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    NOCYCLE
    NOCACHE
;
commit;

SELECT board_no, board_title, nvl(user_name, '탈퇴회원') U_NAME, read_count, enroll_date
from board_tbl 
left join user_tbl on (board_writer = user_no) order by 1 desc;
