-- 사용자 계정 생성하는 방법
-- CREATE USER 계정이름 IDENTIFIED BY 비밀번호
CREATE USER testuser IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO testuser;
REVOKE CONNECT FROM testuser;

CREATE USER ddlexam IDENTIFIED BY 1111;
GRANT CONNECT, RESOURCE TO ddlexam;

DROP USER ddlexam; -- 계정 삭제
