CREATE TABLE USER_TBL(
    USER_NO     NUMBER          PRIMARY KEY,
    USER_ID     VARCHAR2(20)    NOT NULL,
    USER_PW     VARCHAR2(30)    NOT NULL,
    USER_NAME   VARCHAR2(15)    NOT NULL,
    USER_AGE    NUMBER          NOT NULL,
    USER_PHONE  CHAR(13)        NOT NULL,
    UNIQUE(USER_ID)
);
/

COMMENT ON COLUMN USER_TBL.USER_NO IS '회원번호';


COMMENT ON COLUMN USER_TBL.USER_ID IS '아이디';


COMMENT ON COLUMN USER_TBL.USER_PW IS '비밀번호';


COMMENT ON COLUMN USER_TBL.USER_NAME IS '이름';


COMMENT ON COLUMN USER_TBL.USER_AGE IS '나이';


COMMENT ON COLUMN USER_TBL.USER_PHONE IS '전화번호';

CREATE SEQUENCE SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE
;

--  SELECT COUNT(*) FROM USER_TBL WHERE USER_ID = ?

COMMIT;

SELECT * FROM USER_TBL;