GRANT CREATE SYNONYM TO kh;

CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
DROP PUBLIC SYNONYM DEPT;

GRANT SELECT ON KH.DEPARTMENT TO testuser;
GRANT SELECT ON KH.EMPLOYEE TO testuser;

REVOKE SELECT ON KH.DEPARTMENT FROM testuser;