DROP TABLE MEMBERS;
DROP TABLE BOARDS;

CREATE TABLE MEMBERS (
    MEMBER_ID   VARCHAR2(20)        PRIMARY KEY,
    MEMBER_PWD  VARCHAR2(20)        NOT NULL
);

CREATE TABLE BOARDS (
    BOARD_NO        NUMBER          PRIMARY KEY,
    BOARD_WRITER    VARCHAR2(20)    REFERENCES MEMBERS(MEMBER_ID), 
    BOARD_REG_DATE  DATE            DEFAULT SYSDATE
);



 CREATE TABLE MEMBERS(

    MEMBER_ID VARCHAR2(20),
    MEMBER_PWD VARCHAR2(20),
    MEMBER_NAME VARCHAR2(30),
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(50),
    PRIMARY KEY(MEMBER_ID),
    NOT NULL(MEMBER_PWD)
);

CREATE TABLE BOARDS(

BOARD_NO NUMBER PRIMARY KEY,

BOARD_TITLE VARCHAR2(100),

BOARD_CONTENT VARCHAR2(4000),

BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS(MEMBER_ID),

BOARD_REG_DATE DATE DEFAULT SYSDATE

);