ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);
ALTER TABLE "ROOM_REVIEW" ADD CONSTRAINT "PK_ROOM_REVIEW" PRIMARY KEY (
	"R_R_NO"
);

ALTER TABLE "LIFE_REVIEW" ADD CONSTRAINT "PK_LIFE_REVIEW" PRIMARY KEY (
	"LF_R_NO"
);

ALTER TABLE "DINING_REVIEW" ADD CONSTRAINT "PK_DINING_REVIEW" PRIMARY KEY (
	"D_R_NO"
);

SELECT * FROM MEMBER;

CREATE SEQUENCE M_SEQ;
SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE RR_SEQ;
CREATE SEQUENCE DR_SEQ;
CREATE SEQUENCE FR_SEQ;