CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(30)		UNIQUE,
	"MEMBER_PW"	VARCHAR2(30)		NOT NULL,
	"MEMBER_KNAME"	VARCHAR2(40)		NOT NULL,
	"MEMBER_LNAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_FNAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_LEVEL"	NUMBER		NOT NULL,
	"PHONE"	CHAR(13)		NOT NULL,
	"BIRTH"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"ENROLL_DATE"	CHAR(10)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 고유 식별 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디, 유니크 설정필요';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_KNAME" IS '회원 한글이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_LNAME" IS '회원 영문이름(성)';

COMMENT ON COLUMN "MEMBER"."MEMBER_FNAME" IS '회원 영문이름(이름)';

COMMENT ON COLUMN "MEMBER"."MEMBER_LEVEL" IS '회원 등급(관리자 -1  / 브라운-2 /  실버 -3 / 골드 -4 / 다이아몬드 -5)';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."BIRTH" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."POINT" IS '포인트';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일(YYYY-MM-DD)';

CREATE TABLE "ROOM_REVIEW" (
	"R_R_NO"	NUMBER		NOT NULL,
	"REVIEW_WRITER"	VARCHAR2(30)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(800)		NOT NULL,
	"REVIEW_DATE"	CHAR(10)		NOT NULL,
	"STAR"	NUMBER	DEFAULT 0	NOT NULL,
	"RES_NUM"	NUMBER		NOT NULL,
	"ROOM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ROOM_REVIEW"."R_R_NO" IS '리뷰번호';

COMMENT ON COLUMN "ROOM_REVIEW"."REVIEW_WRITER" IS '작성자';

COMMENT ON COLUMN "ROOM_REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "ROOM_REVIEW"."REVIEW_DATE" IS '리뷰 작성일';

COMMENT ON COLUMN "ROOM_REVIEW"."STAR" IS '별점';

COMMENT ON COLUMN "ROOM_REVIEW"."RES_NUM" IS '예약번호';

COMMENT ON COLUMN "ROOM_REVIEW"."ROOM_NO" IS '객실고유식별번호';

CREATE TABLE "LIFE_REVIEW" (
	"LF_R_NO"	NUMBER		NOT NULL,
	"REVIEW_WRITER"	VARCHAR2(30)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(800)		NOT NULL,
	"REVIEW_DATE"	CHAR(10)		NOT NULL,
	"STAR"	NUMBER	DEFAULT 0	NOT NULL,
	"RES_NO"	NUMBER		NOT NULL,
	"LF_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIFE_REVIEW"."LF_R_NO" IS '리뷰번호';

COMMENT ON COLUMN "LIFE_REVIEW"."REVIEW_WRITER" IS '작성자';

COMMENT ON COLUMN "LIFE_REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "LIFE_REVIEW"."REVIEW_DATE" IS '리뷰 작성일';

COMMENT ON COLUMN "LIFE_REVIEW"."STAR" IS '별점';

COMMENT ON COLUMN "LIFE_REVIEW"."RES_NO" IS '예약번호';

COMMENT ON COLUMN "LIFE_REVIEW"."LF_NO" IS '라이프스타일 고유 번호';

CREATE TABLE "DINING_REVIEW" (
	"D_R_NO"	NUMBER		NOT NULL,
	"REVIEW_WRITER"	VARCHAR2(30)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(800)		NOT NULL,
	"REVIEW_DATE"	CHAR(10)		NOT NULL,
	"STAR"	NUMBER	DEFAULT 0	NOT NULL,
	"RES_NO"	NUMBER		NOT NULL,
	"DINING_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DINING_REVIEW"."D_R_NO" IS '리뷰번호';

COMMENT ON COLUMN "DINING_REVIEW"."REVIEW_WRITER" IS '작성자';

COMMENT ON COLUMN "DINING_REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "DINING_REVIEW"."REVIEW_DATE" IS '리뷰 작성일';

COMMENT ON COLUMN "DINING_REVIEW"."STAR" IS '별점';

COMMENT ON COLUMN "DINING_REVIEW"."RES_NO" IS '다이닝 예약번호';

COMMENT ON COLUMN "DINING_REVIEW"."DINING_NO" IS '다이닝 고유 식별 번호';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);
ALTER TABLE "ROOM_REVIEW" ADD CONSTRAINT "PK_ROOM_REVIEW" PRIMARY KEY (
	"R_R_NO"
);

ALTER TABLE "LIFE_REVIEW" ADD CONSTRAINT "PK_LIFE_REVIEW" PRIMARY KEY (
	"LF_R_NO"
);

ALTER TABLE "DINING_REVIEW" ADD CONSTRAINT "PK_DINING_REVIEW" PRIMARY KEY (
	"D_R_NO"
);