SELECT * FROM DINING;
SELECT * FROM LIFESTYLE;
SELECT * FROM ROOM;
SELECT * FROM MEMBER;

SELECT * FROM ROOM_RES WHERE MEMBER_ID='testda';
SELECT * FROM ROOM_REVIEW;
SELECT * FROM LIFE_REVIEW;
SELECT * FROM DINING_REVIEW;

DELETE FROM DINING_REVIEW WHERE REVIEW_WRITER='testda';

SELECT R.ROOM_IMG, RE.RES_NUM CHECK_REVIEW, TO_CHAR(CHECKIN, 'YYYY/MM/DD')TRANSINDATE, TO_CHAR(CHECKOUT, 'YYYY/MM/DD')TRANSOUTDATE, B.* 
FROM (SELECT ROWNUM AS RNUM, A.* FROM (SELECT * FROM ROOM_RES WHERE MEMBER_ID='testda' ORDER BY LPAD(RES_NUM,4,'0') DESC)A)B
JOIN ROOM R ON(R.ROOM_NO = B.ROOM_NO)
LEFT OUTER JOIN ROOM_REVIEW RE ON(B.RES_NUM = RE.RES_NUM)
WHERE RNUM BETWEEN 0 AND 100 ORDER BY LPAD(B.RES_NUM,4,'0') DESC;

SELECT  RE.RES_NUM CHECK_REVIEW, TO_CHAR(CHECKIN, 'YYYY/MM/DD')TRANSINDATE, TO_CHAR(CHECKOUT, 'YYYY/MM/DD')TRANSOUTDATE, B.* 
FROM (SELECT ROWNUM AS RNUM, A.* FROM (SELECT * FROM ROOM_RES  ORDER BY LPAD(RES_NUM,4,'0') DESC)A)B
LEFT OUTER JOIN ROOM_REVIEW RE ON(B.RES_NUM = RE.RES_NUM AND RE.REVIEW_WRITER = B.MEMBER_ID)
WHERE RNUM BETWEEN 0 AND 100 AND MEMBER_ID='testda' ORDER BY LPAD(B.RES_NUM,4,'0') DESC;

ALTER TABLE ROOM_REVIEW ADD ROOM_IMG VARCHAR2(500) NOT NULL;
ALTER TABLE DINING_REVIEW ADD DINING_IMG VARCHAR2(500) NOT NULL;
ALTER TABLE LIFE_REVIEW ADD LIFE_IMG VARCHAR2(500) NOT NULL;



SELECT R.ROOM_IMG, TO_CHAR(CHECKIN, 'YYYY/MM/DD')TRANSINDATE, TO_CHAR(CHECKOUT, 'YYYY/MM/DD')TRANSOUTDATE, B.*, (select count(*) from room_review where res_num = b.res_num) as check_review
FROM (SELECT ROWNUM AS RNUM, A.* FROM (SELECT * FROM ROOM_RES WHERE MEMBER_ID='testda' ORDER BY LPAD(RES_NUM,4,'0') DESC)A)B
LEFT JOIN ROOM R ON(R.ROOM_NO = B.ROOM_NO)
WHERE RNUM BETWEEN 0 AND 100;

SELECT * FROM ROOM_RES WHERE MEMBER_ID='testda';
select * from room_review;


SELECT B.THUMBNAIL_IMG TI, DR.RES_NO CHECK_REVIEW, B.DINING_NAME DN, TO_CHAR(DE.RES_DATE, 'YYYY/MM/DD')TRANSDATE, DE.* 
FROM (SELECT ROWNUM AS RNUM, D.* FROM(SELECT * FROM DINING_RES WHERE MEMBER_ID='testda' ORDER BY LPAD(RES_NO,4,'0') DESC)D)DE 
JOIN DINING B ON (DE.DINING_NO = B.DINING_NO) 
LEFT OUTER JOIN DINING_REVIEW DR ON(DE.RES_NO = DR.RES_NO)
WHERE RNUM BETWEEN 0 AND 10 ORDER BY LPAD(DE.RES_NO,4,'0') DESC;

commit;

SELECT * FROM MEMBER;


SELECT * FROM ROOM_REVIEW;

INSERT INTO QUESTION 
VALUES(Q_SEQ.NEXTVAL, DEFAULT, '문의', 1, '테스트하는중', 0, 'FILE', to_char(sysdate,'yyyymmdd'), '테스트가 너무나 잘되기를 제발', '테스트', 'min9288@gmail.com', '010-1234-5487', '02-123-4567', 'AUTO'); 
/*
R12
R9
R11
R13
R10
*/